---
name: bookly
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  font_awesome_flutter: 10.3.0
  google_fonts: ^4.0.1
  go_router: ^6.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  get_it: ^7.2.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.8
  dependencies:
  scroll_snap_list: ^0.9.1
  animated_text_kit: ^4.2.2
  liquid_progress_indicator: ^0.4.0
  like_button: ^2.0.5
  shared_preferences: ^2.0.17
  avatar_glow: ^2.0.2
  social_media_flutter: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/images/
